# matrix :

In [1]:
import numpy as np

In [2]:
var = np.matrix([[1,2,3],[4,5,6]])

print(var)
print(type(var))

[[1 2 3]
 [4 5 6]]
<class 'numpy.matrix'>


In [3]:
var = np.array([[1,2,3],[4,5,6]])

print(var)
print(type(var))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


# Addition

In [10]:
a = np.matrix([[1,2,3],[4,5,6]])
b = np.matrix([[6,5,4],[3,2,1]])

print(a)
print(b)
print()
print(a + b)

[[1 2 3]
 [4 5 6]]
[[6 5 4]
 [3 2 1]]

[[7 7 7]
 [7 7 7]]


In [5]:
print(a - b)

[[-5 -3]
 [ 1  3]]


In [6]:
print(a * b)

[[12  9]
 [39 30]]


In [7]:
print(a.b)

AttributeError: 'matrix' object has no attribute 'b'

In [ ]:
var = np.matrix([[1,2,3],[4,5,6]])

var1 =

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [13]:
print(a.dot(b))

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [20]:
var = np.matrix([[1,2],[4,5]])
var2 = np.matrix([[3,2],[6,5]])


res = np.matmul(var2,var)
res

matrix([[11, 16],
        [26, 37]])

# transpose of matrix

In [21]:
var = np.matrix([[1,2,3],[4,5,6]])
print(var)

[[1 2 3]
 [4 5 6]]


In [23]:
print(var.transpose())

[[1 4]
 [2 5]
 [3 6]]


In [24]:
print(np.transpose(var))

[[1 4]
 [2 5]
 [3 6]]


In [25]:
print(var)

[[1 2 3]
 [4 5 6]]


In [26]:
print(var.T)

[[1 4]
 [2 5]
 [3 6]]


# swapaxes 


In [28]:
print(var.swapaxes(0,1))

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
np.swapaxes(var,1,0)

matrix([[3, 6],
        [2, 5]])

In [38]:
a = np.matrix([[1,2,3],[4,5,6]])
b = np.matrix([[3,2,1],[6,5,4]])

print(np.swapaxes(a,0,1))

[[1 4]
 [2 5]
 [3 6]]


In [40]:
print(np.swapaxes(b,1,0))

[[3 6]
 [2 5]
 [1 4]]


# Inverse matrix

In [45]:
var3 = np.matrix([[1,2],[3,4]])
print(var3)
print('*' * 50)
print(np.linalg.inv(var3))


[[1 2]
 [3 4]]
**************************************************
[[-2.   1. ]
 [ 1.5 -0.5]]


In [46]:
import random

In [47]:
import random 

subjects = [
    "Narendra Modi",      
    "Rahul Gandhi",       
    "Shahrukh Khan",      
    "Salman Khan",        
    "Virat Kohli",       
    "PV Sindhu",          
    "Sachin Tendulkar",   
    "Deepika Padukone",   
    "Priyanka Chopra",    
    "MS Dhoni"            
]


actions = [
    "playing cricket",
    "swimming",
    "dancing",
    "singing",
    "giving a speech",
    "acting in a movie",
    "attending an event",
    "posing for a photo",
    "meeting fans",
    "traveling"
]

things_places = [
    "Gateway of India",
    "Taj Mahal",
    "Red Fort",
    "Marine Drive",
    "Ajanta Caves",
    "Elephanta Caves",
    "Lonavala",
    "Mahabaleshwar",
    "Goa Beach",
    "Ranthambore National Park",
    "shopping mall",
    "stadium",
    "political rally",
    "film set",
    "cricket ground",
    "music concert",
    "conference hall",
    "charity event",
    "dance stage",
    "temple visit"
]

# 3 start headline generation loop

while True:
    subject = random.choice(subjects)
    action = random.choice(actions)
    things_place = random.choice(things_places)

    headline = f" Breaking news : {subject} {action} {things_place}."

    print("\n" + headline)

    user_input = input("\n Do you want another headline? (yes/no)").strip().lower()

    if user_input == "no":
        break

print("\n thanks for using fake news headline generator.Have a fun... ")


 Breaking news : Rahul Gandhi meeting fans shopping mall.

 Breaking news : Salman Khan dancing charity event.

 Breaking news : Shahrukh Khan posing for a photo dance stage.

 Breaking news : Shahrukh Khan acting in a movie temple visit.

 Breaking news : Sachin Tendulkar giving a speech temple visit.

 Breaking news : Rahul Gandhi giving a speech Elephanta Caves.

 Breaking news : Shahrukh Khan posing for a photo film set.

 Breaking news : MS Dhoni singing stadium.

 thanks for using fake news headline generator.Have a fun... 


In [1]:
'hello'

'hello'